---
  - hosts: kube-3-master
    vars:
      join_token: "e172b1.34b5ee4547657e38"
      master_ip: "138.197.134.8"

    tasks:
      - name: "create kubernetes cluster"
        shell: kubeadm init --pod-network-cidr 10.244.0.0/16 --skip-preflight-checks
        args:
          executable: /bin/bash
        #     become: yes
        #   become_user: root

      - name: "Initialize flannel"
        shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
        args:
          executable: /bin/bash

      - name: "Initialize kubernetes dashboard"
        shell: kubectl apply -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
        args:
          executable: /bin/bash
