---
  - vars:
      hosts: kube

    hosts: "{{ hosts }}"

    tasks:
      - name: start docker
        service:
          name: docker
          state: started
        become: yes
        become_user: root

      - name: "create kubernetes cluster"
        shell: kubeadm init --pod-network-cidr 10.244.0.0/16
        args:
          executable: /bin/bash

      - name: "Initialize canal"
        shell: KUBECONFIG=/etc/kubernetes/admin.conf && kubectl apply -f https://raw.githubusercontent.com/projectcalico/canal/master/k8s-install/1.7/rbac.yaml
        args:
          executable: /bin/bash

      - name: "Initialize canal"
        shell: KUBECONFIG=/etc/kubernetes/admin.conf && kubectl apply -f https://raw.githubusercontent.com/projectcalico/canal/master/k8s-install/1.7/canal.yaml
        args:
          executable: /bin/bash

      - name: "Initialize kubernetes dashboard"
        shell: KUBECONFIG=/etc/kubernetes/admin.conf && kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
        args:
          executable: /bin/bash
