---
  - vars:
      hosts: kube
      join_token: ""
      master_ip: ""
      cert_hash: ""

    hosts: "{{ hosts }}"

    tasks:
      - name: start docker
        service:
          name: docker
          state: started
        become: yes
        become_user: root

      # kubeadm token create --print-join-command

      - name: "joining kubernetes cluster"
        shell: "kubeadm join --token={{ join_token }} {{ master_ip }} --discovery-token-ca-cert-hash {{cert_hash}}"
        args:
          executable: /bin/bash
        #     become: yes
        #   become_user: root
