---
  - vars:
      docker_iptables: false
      install_docker_compose: false
      hosts: "gitlab-runner"
      registration_token: ""
      runner_name: "docker-runner"
      registration_url: "https://gitlab.com/ci"

    hosts: "{{ hosts }}"
    roles:
      - docker

    tasks:
      - name: "runner gitlab setup script"
        shell: "curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | sudo bash"
        args:
          executable: /bin/bash
        become: yes

      - name: Install gitlab runner
        apt: name={{item}} state=present update_cache=yes
        with_items:
          - gitlab-ci-multi-runner
        become: yes

      - name: "registrating with gitlab server"
        shell: "gitlab-runner register -n --name {{ runner_name }} -u {{ registration_url }} -r {{ registration_token }} --executor docker --docker-image docker --docker-volumes '/var/run/docker.sock:/var/run/docker.sock' --tag-list 'docker, docker-build'"
        args:
          executable: /bin/bash
        become: yes
