---
- hosts: server

  vars:
    user_name: admin
    package_to_install:
      - ufw
      - fail2ban
      - unattended-upgrades
      # - logwatch
    ssh_port: 22

  vars_prompt:
    - name: user_password
      prompt: "Enter password for user admin"
      confirm: yes
      private: yes

  tasks:

    - name: Create admin user
      user:
        name={{user_name}}
        state=present
        shell=/bin/bash
        password="{{ user_password }}"

    - name: add ssh keys
      authorized_key:
        user=admin
        key={{ lookup('file', item) }}
        state=present
      with_fileglob:
        - ../../ssh-public-keys/*

    - name: Add deploy user to sudoers
      lineinfile: dest=/etc/sudoers
        regexp="{{ user_name }} ALL"
        line="{{ user_name }} ALL=(ALL) ALL"
        state=present

    - name: Update APT package cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Install required packages
      apt: state=installed pkg={{ item }}
      with_items: "{{package_to_install}}"

    - name: Adjust APT update intervals
      copy: src=files/apt_periodic dest=/etc/apt/apt.conf.d/10periodic

    - name: Allow ssh traffic through firewall
      ufw: rule=allow port={{ ssh_port }} proto=tcp

    - name: Setup ufw
      ufw: state=enabled policy=deny

    - name: Change ssh port
      lineinfile: dest=/etc/ssh/sshd_config
        regexp="^Port\s"
        line="Port {{ ssh_port }}"
        state=present
      notify: Restart ssh

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
        regexp="^PasswordAuthentication"
        line="PasswordAuthentication no"
        state=present
      notify: Restart ssh

    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
        regexp="^PermitRootLogin"
        line="PermitRootLogin no"
        state=present
      notify: Restart ssh

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
